### PR TITLE
feat: update vuepress to next version

### PR DESCRIPTION
**Pull request by laoergege**
I change some codes for updating to the vuepress-next. But there is a cypress error that I don't know why.

Imgur

```txt
1) renders diagrams:
     RangeError: The value of "offset" is out of range. It must be >= 0 and <= 3686396. Received -3680
  RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3686396. Received -3680
      at boundsError (internal/buffer.js:72:9)
      at Buffer.readUInt32BE (internal/buffer.js:295:5)
      at Jimp.<anonymous> (/Users/lianyuansheng/Library/Caches/Cypress/4.12.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@jimp/plugin-crop/dist/index.js:43:37)
      at scan (/Users/lianyuansheng/Library/Caches/Cypress/4.12.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@jimp/utils/dist/index.js:53:9)
      at Jimp.scanQuiet (/Users/lianyuansheng/Library/Caches/Cypress/4.12.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@jimp/core/dist/index.js:1262:32)
      at Jimp.cropQuiet (/Users/lianyuansheng/Library/Caches/Cypress/4.12.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@jimp/plugin-crop/dist/index.js:42:12)
      at Jimp.<computed> [as crop] (/Users/lianyuansheng/Library/Caches/Cypress/4.12.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@jimp/core/dist/index.js:1176:23)
      at crop (/Users/lianyuansheng/Library/Caches/Cypress/4.12.1/Cypress.app/Contents/Resources/app/packages/server/lib/screenshots.js:161:24)
      at /Users/lianyuansheng/Library/Caches/Cypress/4.12.1/Cypress.app/Contents/Resources/app/packages/server/lib/screenshots.js:435:17
```

### CODE REVIEW

**Comment by laoergege** [comment]
Sorry :sweat_smile: , I do not think more because I only use the vuepress@next,  your thinking is right. It is sure that we must publish two versions for this plugin to adapt different Vue. I recommend the Monorepo Solution. So how do we do next?

**Comment by JohannesRudolph** [comment]
Coming from a user of vuepress@next here - I don't mind any particular approach to packaging or maintenance as long as there's clear install instructions for each version of vuepress :-) 

I may be ignorant of the complexity and burden of maintaining this plugin (sorry @eFrane ;-) ) but it looks like the meat of the implementation lives in https://github.com/eFrane/vuepress-plugin-mermaidjs/blob/master/src/markdownItPlugin.js which is just shy of 140 lines. The rest looks like it's all the vuepress specific plugin logic. At that point I wouldn't mind if it's even two totally separate packages (and or repos), as porting changes between either is probably not going to be that hard. If I'd be using the vuepress-next version and I hit a bug on the issue tracker here that was fixed on v1, I'd probably be able to volley a PR that ports it to the vnext branch. 

Does that make any sense?

**Comment by JohannesRudolph** [comment]
@laoergege I've been testing this and have noticed the following issues

- mermaid is being invoked during SSR build under node. However, mermaid only works in browser. You will hence see errors like `document is undefined` etc. during SSR builds
- the hydration of the Mermaid component is also not working properly. This means that when loading a page containing a mermaid diagram directly (from SSR), the loading spinner will never disappear. The same page works fine when rendering client side (e.g. by navigating away from it and back). 

Both issues can be fixed by wrapping the Mermaid component in `ClientOnly` from the markdown-it plugin

```
     // mermaid does not work in node, hence we need to wrap it with ClientOnly, see https://v2.vuepress.vuejs.org/reference/components.html#clientonly
     return `<ClientOnly><Mermaid id="${key}"></Mermaid></ClientOnly>` 
```

There may be a better way to do this, e.g. to get the loading spinner into the SSR output already (so that it's visible on first page load?) and move that into the Mermaid component itself. However, I'm afraid I don't know enough about vue.js and its SSR hydration specialties to get that working.

**Comment by eFrane** [comment]
I just pushed changes to `master` that should massively simplify supporting vuepress-next. For a while now, I was disappointed with the complexity of the markdown-it plugin when really it's only job is to replace mermaid fenced code blocks with the appropriate component tag. 

As @JohannesRudolph pointed out, Mermaid rendering has to happen in the browser. Currently, this is achieved by dynamically requiring mermaid import during the `Mermaid` component rendering which in my experience makes the whole thing ignore SSR.

This PR is still a great start though. I'm hopeful that "official" support for vuepress-next aka version 2 of this plugin will be released rather soonish.

**Comment by eFrane** [comment]
@laoergege Thank you for your contribution as it helped in finally closing #64. Unfortunately, I was not able to make it work as is.

**Pull request closed without merging**
